### ISSUE TITLE
의존성 패키지

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Avatar-Web#1]
debian sid 에서는 `libgd-dev` 를 설치하면 `GD` 모듈을 설치할 수 있었습니다.

하지만 실제 서버의 debian version 은 `7.9` 입니다.

```
$ sudo apt-get install libgd-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgd-dev is a virtual package provided by:
  libgd2-xpm-dev 2.0.36~rc1~dfsg-6.1+deb7u1
  libgd2-noxpm-dev 2.0.36~rc1~dfsg-6.1+deb7u1
You should explicitly select one to install.

E: Package 'libgd-dev' has no installation candidate
```

어떤 패키지를 설치해야 할지 알아야 합니다.

**Comment by aanoaa** [comment]
lxc 에서 패키지 설치 어떻게 하나요?
그냥 똑같이?
컨테이너 밖에서?

**Comment by yongbin** [comment]
> lxc 에서 패키지 설치 어떻게 하나요?
> 그냥 똑같이?
> 컨테이너 밖에서?

완전히 동일합니다. sudo apt-get install 로 진행하시면 됩니다.

**Comment by aanoaa** [comment]
`libgd2-xpm-dev` 를 설치하려고 시도 했는데 실패했습니다.

**Comment by aanoaa** [comment]
graphic library 를 `Imlib2-dev` 를 사용하도록 하겠습니다.
리사이징만 되면 되기 때문에 무엇을 쓰던지 상관없습니다.
